import { InfoLdg } from "types";

export const infos: InfoLdg[] = [
  {
    title: "Empower Your Knowledge, Elevate Your Intelligence",
    description:
      "A cutting-edge AI-enhanced SaaS platform to revolutionize knowledge management. Streamline data access, enhance accuracy, and unlock intellectual potential with our advanced tools. Empower your knowledge and elevate your intelligence with AIIntellectHub. Discover the future of information management today",
    image: "/images/work-from-home.jpg",
    list: [
      {
        title: "Efficiency",
        description: "Speeds up data access and organization, vastly reducing time spent on management tasks.",
        icon: "laptop",
      },
      {
        title: "Insightfulness",
        description: "Unlocks deep data insights, enabling better-informed decisions through advanced AI analysis.",
        icon: "settings",
      },
      {
        title: "Versatility",
        description:
          "Adapts across various departments, fostering seamless collaboration and knowledge sharing within organizations.",
        icon: "search",
      },
    ],
  },
  {
    title: "Seamless Integration",
    description:
      "Integrate our open-source SaaS seamlessly into your existing workflows. Effortlessly connect with your favorite tools and services for a streamlined experience.",
    image: "/images/work-from-home.jpg",
    list: [
      {
        title: "Flexible",
        description:
          "Customize your integrations to fit your unique requirements.",
        icon: "laptop",
      },
      {
        title: "Efficient",
        description: "Streamline your processes and reducing manual effort.",
        icon: "search",
      },
      {
        title: "Reliable",
        description:
          "Rely on our robust infrastructure and comprehensive documentation.",
        icon: "settings",
      },
    ],
  },
];

export const features = [
  {
    title: "Feature 1",
    description:
      "Amet praesentium deserunt ex commodi tempore fuga voluptatem. Sit, sapiente.",
    link: "/",
  },
  {
    title: "Feature 2",
    description:
      "Amet praesentium deserunt ex commodi tempore fuga voluptatem. Sit, sapiente.",
    link: "/",
  },
  {
    title: "Feature 3",
    description:
      "Amet praesentium deserunt ex commodi tempore fuga voluptatem. Sit, sapiente.",
    link: "/",
  },
  {
    title: "Feature 4",
    description:
      "Amet praesentium deserunt ex commodi tempore fuga voluptatem. Sit, sapiente.",
    link: "/",
  },
  {
    title: "Feature 5",
    description:
      "Amet praesentium deserunt ex commodi tempore fuga voluptatem. Sit, sapiente.",
  },
  {
    title: "Feature 6",
    description:
      "Amet praesentium deserunt ex commodi tempore fuga voluptatem. Sit, sapiente.",
    link: "/",
  },
];

export const testimonials = [
  {
    name: "John Smith",
    job: "Full Stack Developer",
    image: "https://randomuser.me/api/portraits/men/1.jpg",
    review:
      "AIIntellectHub has fundamentally changed the way we handle data. The AI-driven insights have improved our decision-making process considerably. A game-changer for our business!",
  },
  {
    name: "Emily Davis",
    job: "UI/UX Designer",
    image: "https://randomuser.me/api/portraits/women/2.jpg",
    review:
      "The platform's user interface is incredibly intuitive. I was able to onboard my team within a couple of days, and we've seen productivity skyrocket. Highly recommend AIIntellectHub!",
  },
  {
    name: "Michael Chen",
    job: "DevOps Engineer",
    image: "https://randomuser.me/api/portraits/men/3.jpg",
    review:
      "I was skeptical about migrating over to a new knowledge management system, but AIIntellectPage has exceeded my expectations. The accuracy and speed of information retrieval are unmatched.",
  },
  {
    name: "Sara Johnson",
    job: "Project Manager",
    image: "https://randomuser.me/api/portraits/men/5.jpg",
    review:
      "As a small business owner, AIIntellectHub has given me access to powerful tools that I thought were only available to large corporations. It's affordable and very effective.",
  },
  {
    name: "Alex Martinez",
    job: "Data Analyst",
    image: "https://randomuser.me/api/portraits/women/6.jpg",
    review:
      "Initially impressed with the platform's capabilities, but I've experienced some issues with customer support response times. The product is great, but I hope they improve their service.",
  },
  {
    name: "Natalie Wong",
    job: "Marketing Manager",
    image: "https://randomuser.me/api/portraits/women/4.jpg",
    review:
      "The insights generated by AIIntellectHub have been crucial for our market research. The ability to quickly process and analyze large sets of data is impressive.",
  },
  {
    name: "Daniel Brown",
    job: "Web Designer",
    image: "https://randomuser.me/api/portraits/men/9.jpg",
    review:
      "I've used several knowledge management tools, and AIIntellectHub is by far the most advanced. The AI features not only save time but also uncover insights that would have been missed otherwise.",
  },
];
